### PR TITLE
detect: Added cpuInfo method to use cpu info for host detection.

### PR DESCRIPTION
**Pull request by benjamind**
Potential fix for #16 using cpuInfo contents instead of uname. Have tested this on a BBB, but I don't have a Raspberry Pi handy to confirm. Can someone please check on a Pi?

### CODE REVIEW

**Comment by kidoman** [comment]
Thanks for this :) Have pushed it as https://github.com/kidoman/embd/commit/bf6e647c1d100ac046004bf1777429f6f67f9dbd

**Comment by benjamind** [comment]
No problem at all, did it work on the Pi?

**Comment by kidoman** [comment]
See for yourself:

```
➜  samples git:(master) ✗ GOOS=linux GOARCH=arm go install github.com/kidoman/embd/embd
➜  samples git:(master) ✗ scp -C $GOPATH/bin/linux_arm/embd pi@rpi:~

pi@raspberrypi ~ $ ./embd detect
detected host Raspberry Pi (rev 0x10)
pi@raspberrypi ~ $
```

**Comment by benjamind** [comment]
Awesome.  Thanks.

**Pull request closed without merging**
